swagger: '2.0'
info:
  version: '1.0'
  title: 'foo'
  description: |
    `Foo Service` -- 提供...服务

    ## 约定

    - 命名中英文无论单复数尽量统一用单数形式
    - 表示时间的字符串如无特别说明，统一指 RFC3339 UTC 格式，示例： `2017-05-30T01:45:39.871980Z`

host: localhost:3000
schemes:
- http

tags:

- name: notice
  description: 通知

paths:

  "/_spec":
    get:
      tags:
      - default
      summary: 获取 YAML 格式的 SwaggerUI 文档（即本文档）
      produces:
      - application/yaml
      responses:
        "200":
          description: 返回 YAML 文档

  "/_health":
    get:
      tags:
      - default
      summary: 查看健康状态
      responses:
        "200":
          description: 返回 "ok" 表示服务运行健康

  "/sms":

    parameters:
    - $ref: '#/parameters/Authorization'

    post:
      tags:
      - notice
      summary: 发送短信验证码
      parameters:
      - name: body
        in: body
        schema:
          type: object
          required:
          - phone
          - template_id
          - template_args
          properties:
            phone:
              type: string
              description: 手机号码
              minLength: 11
              maxLength: 11
            template_id:
              type: integer
              description: 调用模版 id
            template_args:
              type: object
              description: 通知内容，字典中的 value 为 int 或者 str
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
                default: "success"
        default:
          description: |
            返回错误信息
          schema:
            $ref: '#/definitions/DefaultErrorResponse'

  "/email":

    parameters:
    - $ref: '#/parameters/Authorization'

    post:
      tags:
      - notice
      summary: 发送邮件验证码
      parameters:
      - name: body
        in: body
        schema:
          type: object
          required:
          - email
          - template_name
          - template_args
          properties:
            email:
              type: string
              description: 邮件地址
            template_name:
              type: string
              description: 调用模版名称
            template_args:
              type: object
              description: 通知内容，字典中的 value 为 int 或者 str

      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
                default: "success"
        default:
          description: |
            返回错误信息
          schema:
            $ref: '#/definitions/DefaultErrorResponse'


definitions:

  DefaultErrorResponse:
    type: object
    required:
    - status
    properties:
      status:
        type: string
        description: 错误字符串
      message:
        type: string
        description: 错误描述信息
      errors:
        type: string
        description: 有多个错误值时（通常发生在验证表单失败时）
      data:
        type: object
        properties:
          status_code:
            type: integer
            format: int
            description: 错误码
          exc_info:
            type: string
            description: 详细错误信息


parameters:

  Authorization:
    name: Authorization
    in: header
    type: string
    description: 提供 JWT Token, 格式 `"Bearer {TOKEN}"`
    required: true
